project:
  type: website

website:
  title: "Visual Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - text: "Topics"
        menu: 
          - text: Fundamentals of ggplot2
            href: Topics/HO1/HO1.html
          - text: Extensions of ggplot2
            href: Topics/HO2/HO2.html
          - text: xx
      - text: "Exercises"
        menu: 
          - text: xx
            href: Topics/IC1/IC1.html
      - text: "Projects"
        menu:
          - text: xx
    
  page-navigation: true

  back-to-top-navigation: false
  
  page-footer:
    background: "#ABEBC6"
    center:
      - href: https://chockwk-visual-analytics.netlify.app
        icon: house-fill
        aria-label: Home
      - href: wkchock.2022@mitb.smu.edu.sg
        icon: envelope-fill
        aria-label: Email
      - href: https://github.com/chockwk/ISSS624_Geospatial_Analytics/tree/main
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/in/wan-kee/
        icon: linkedin
        aria-label: LinkedIn

        

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual